Repository RGB-WG/rgb, pull requests merged in 2024-07, with the labels that each got.

#216 Refactor runtime and fs persistence
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/src/args.rs
  cli/src/command.rs
  src/errors.rs
  src/indexers/any.rs
  src/indexers/electrum_blocking.rs
  src/indexers/esplora_blocking.rs
  src/indexers/mod.rs
  src/lib.rs
  src/pay.rs
  src/store.rs
  src/wallet.rs
  src/wrapper.rs
Labels: enhancement

#217 Use signer branch on BP crates
  Cargo.lock
  Cargo.toml
  psbt/src/lib.rs
  src/descriptor.rs
  src/indexers/mempool_blocking.rs
  src/wallet.rs
Labels: enhancement

#223 Descriptor: fix encofced keychains value for Tapret
  src/descriptor.rs
Labels: bug

#226 make rgb-std's fs feature optional in rgb
  Cargo.toml
Labels: ci

#224 Update to use enum-based PubWitness type from std lib
  Cargo.lock
  Cargo.toml
  src/indexers/any.rs
Labels: enhancement
