Repository RGB-WG/rgb, pull requests merged in 2024-09, with the labels that each got.

#240 Use just single secret seal in payments
  Cargo.lock
  Cargo.toml
  src/pay.rs
Labels: enhancement

#241 esplora indexer: detect mempool TXs
  src/indexers/esplora_blocking.rs
Labels: bug

#242 Fix version used in printing out PSBT
  cli/src/command.rs
Labels: bug

#238 Use new StoreProvider APIs
  .github/workflows/build.yml
  Cargo.lock
  Cargo.toml
  cli/src/args.rs
  cli/src/command.rs
  src/errors.rs
  src/pay.rs
  src/wallet.rs
  src/wrapper.rs
Labels: epic

#250 Fix Windows builds in CI
  .github/workflows/build.yml
  .github/workflows/test.yml
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  src/wallet.rs
Labels: ci
